version: 2.1

jobs:
  build-and-push:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t orozali/bankApp-backend:v1 .
            echo "$DOCKERHUB_PASSWORD" | docker login --username orozali --password-stdin
            docker push orozali/restaurant-backend:v1
  pull-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install SSH And Configure
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ./Orozali.pem
            chmod 400 Orozali.pem
      - run:
          name: Pull Image and Deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./Orozali.pem ubuntu@$HOST '
            sudo docker pull orozali/bankApp-backend:v1
            sudo docker run -d -p 80:8080 orozali/bankApp-backend:v1
            '
workflows:
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
      - pull-and-deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: master